truss_data <- read.table("metalTrussData.txt", header = TRUE)
attach(truss_data)
str(truss_data)
summary(aov(Stiffness.kips.in.. ~ factor(PlateLength)))
truss_data
detach(truss_data)

grain_data <- read.table("grainData.txt", header = TRUE)
attach(grain_data)
str(grain_data)
summary(aov(ThiaminContent ~ Grain))
detach(grain_data)

lab_data <- read.table("Lab_MethylAlchohol_Data.txt", header = TRUE)
attach(lab_data)
str(lab_data)
boxplot(Percentage.Alchohol ~ Lab, main = "Alchohol Percent")
summary(aov(Percentage.Alchohol ~ factor(Lab)))
detach(lab_data)

weight_gain_data <- read.table("weightgain.txt", header = TRUE)
attach(weight_gain_data)
str(weight_gain_data)
boxplot(weightgain ~ group, main = "Weight Gain per Group", ylab = "Weight Gain", xlab = "Group")
qqnorm(weightgain, main = "Normal Q-Q Plot of Weight Gain")
qqline(weightgain)
weight_gain_anova <- aov(weightgain ~ factor(group))
TukeyHSD(weight_gain_anova)
tapply(weightgain,group, mean)
detach(weight_gain_data)

lifetimes_data <- read.table("lifetimes.txt", header = TRUE)
attach(lifetimes_data)
str(lifetimes_data)
summary(aov(lifetime ~ factor(brand)))
detach(weight_gain_data)
