plant_growth_by_type <- read.table("PlantGrowth.txt", header = TRUE)
attach(plant_growth_by_type)
str(plant_growth_by_type)
boxplot(PlantGrowth ~ Type, xlab = "Type of Hormone", 
        ylab = "Plant Growth")
qqnorm(PlantGrowth, main = "Normal Q-Q Plot of PlantGrowth")
qqline(PlantGrowth)
plant_anova <- (aov(PlantGrowth ~ factor(Type)))
summary(plant_anova)
TukeyHSD(plant_anova)
tapply(PlantGrowth, Type, mean)
detach(plant_growth_by_type)

salinity_level_table <- read.table("SalinityVSElectricalConductivity.txt", header = TRUE)
attach(salinity_level_table)
str(salinity_level)
boxplot(Salinity_Level ~ Electrial_Conductivity, 
        xlab = "Electrical Conductivity", ylab = "Salinity Level")
qqnorm(salinity_level_table$Salinity_Level, main = "Normal Q-Q Plot of Salinity Level")
qqline(salinity_level_table$Salinity_Level)
salinity_anova <- (aov(Salinity_Level ~ factor(Electrial_Conductivity)))
summary(salinity_anova)
TukeyHSD(salinity_anova)
tapply(salinity_level_table$Salinity_Level, salinity_level_table$Electrial_Conductivity, mean)
detach(salinity_level_table)

folicin_table <- read.table("TeaBrandVSFolacinContent.txt", header=TRUE)
attach(folicin_table)
boxplot(Folacin_Content ~ Tea_Brand, main = "Folicin Content vs Tea Brand", xlab = "Tea Brand",
        ylab = "Folicin Content")
qqnorm(Folacin_Content, main = "Normal Q-Q Plot Folacin Content")
qqline(Folacin_Content)
folacin_anova <- aov(Folacin_Content ~ factor(Tea_Brand))
summary(folacin_anova)
TukeyHSD(folacin_anova)
tapply(Folacin_Content, Tea_Brand, mean)

weight_gain_data <- read.table("weightgain.txt", header = TRUE)
attach(weight_gain_data)
str(weight_gain_data)
boxplot(weightgain ~ group, main = "Weight Gain per Group", ylab = "Weight Gain", xlab = "Group")
qqnorm(weightgain, main = "Normal Q-Q Plot of Weight Gain")
qqline(weightgain)
weight_gain_anova <- aov(weightgain ~ factor(group))
TukeyHSD(weight_gain_anova)
tapply(weightgain,group, mean)
detach(weight_gain_data)

lifetimes_data <- read.table("lifetimes.txt", header = TRUE)
attach(lifetimes_data)
str(lifetimes_data)
boxplot(lifetime ~ brand, main = "Lifetimes vs Brand", xlab = "Brand", ylab = "Lifetime")
qqnorm(lifetime, main = "Normal Q-Q Plot of Lifetime")
qqline(lifetime)
lifetime_aov <- aov(lifetime ~ factor(brand))
TukeyHSD(lifetime_aov)
tapply(lifetime, brand, mean)
detach(weight_gain_data)
